### ISSUE TITLE
Compilation error: 'AVI_open_input_file' was not declared in this scope

### ISSUE THREAD

**Issue by Ynilaje96** [moononournation/aviPlayer#1]
Hello there,

I’m an engineering student working on a project using the LilyGO T-Display S3 model, and during my research, I noticed the AVI library in your repository. In the AviMjpeg_JPEGDEC example, there are some errors related to AVI_open_input_file. I’d like to know if this is an unfinished feature. I saw that you made a commit 4 days ago, so I’m guessing there might be some updates in the future. Thank you for your work!

![Captura de tela 2024-08-26 153836](https://github.com/user-attachments/assets/8c542a09-5270-41da-b555-9179b9754d6c)

**Comment by moononournation** [comment]
had you fulfilled the dependency libraries setup?

**Comment by Ynilaje96** [comment]
> had you fulfilled the dependency libraries setup?

I downloaded the libraries related to AVI:

- avilib.h and defs.h.
-The GFX library is already updated as well. 

Is there any other library I need to install or download to complete the setup?
