### ISSUE TITLE
LilyGo T4-S3 Amoled compatibility

### ISSUE THREAD

**Issue by richgain** [moononournation/aviPlayer#2]
Hi again,
You previously helped me to get AVI files working by directing me to https://github.com/moononournation/aviPlayer/tree/main/AviMp3CinepakDMA, but I see that this has now disappeared from your GIT repository.

I am currently working on getting AVI files to play on the LilyGo T4-S3 Amoled. 
I have a version of AviMp3Cinepak that plays the video frames but the audio doesn't work. 
Your recent Instructable article for the LilyGo T-Deck (with a suitable pin definition file for T4-S3) successfully plays the audio component of the AVI files, but doesn't play the video frames.

Is there a recommended version of your code for playing AVI files on this device?
Thank you.

**Comment by moononournation** [comment]
I think all should work.
